### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by yukkikou** [AdrianSeguraOrtiz/MO-GENECI#1]
Hi, I didn't find the latest version when I installed MO-GENECI. 
```
pip index versions geneci
WARNING: pip index is currently an experimental command. It may be removed/changed in a future release without prior warning.
geneci (1.5.1)
Available versions: 1.5.1, 1.0.1
  INSTALLED: 1.5.1
  LATEST:    1.5.1
```

**Comment by AdrianSeguraOrtiz** [comment]
Hi Xueyan Hu,

Thank you so much for using my tool. I’ve read your message, and I find it curious what you’re describing. I ran some tests on my system, and the latest version seems to be available without any issues. I’m sharing a screenshot for your reference:

![mo-geneci-versions](https://github.com/user-attachments/assets/c44a40e5-1eb0-48b8-b9c3-31f2027f73c2)

Additionally, the version is published on PyPI: [https://pypi.org/project/GENECI/2.0.1/](https://pypi.org/project/GENECI/2.0.1/). Perhaps updating pip or making some adjustments could help detect it correctly.

**Comment by yukkikou** [comment]
Thank you very much for your quick reply. I have successfully installed MO-GENECI. 
By the way, during the installation I did not find the required scipy version == ‘^1.10.2’, but the higher version 1.11.2 seems to work well too.
